// <auto-generated />
namespace MultipleDbContextDemo.MigrationsSecond
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Demo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Demo));
        
        string IMigrationMetadata.Id
        {
            get { return "202112170734309_Demo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
